import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * KOSMOS V2.0 Documentation Sidebars
 *
 * Multiple sidebars for different documentation sections:
 * - Getting Started: Installation, quick start, configuration
 * - Architecture: System design, governance, data layer
 * - Agents: 11 specialized agents (auto-generated)
 * - API: REST API reference (auto-generated from FastAPI)
 * - MCP Servers: 88 MCP servers (auto-generated)
 * - Frontend: React components (auto-generated)
 * - Database: Schema documentation (auto-generated)
 * - Configuration: Environment variables (auto-generated)
 * - Governance: Gap analysis, roadmap, contributing
 */
const sidebars: SidebarsConfig = {
  // Getting Started Sidebar (Manual)
  gettingStartedSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
        title: 'Getting Started with KOSMOS V2.0',
        description: 'Learn how to install, configure, and start using KOSMOS V2.0',
        slug: '/01-getting-started',
      },
      items: [
        {type: 'autogenerated', dirName: '01-getting-started'},
      ],
    },
  ],

  // Architecture Sidebar (Manual)
  architectureSidebar: [
    {
      type: 'category',
      label: 'Architecture',
      link: {
        type: 'generated-index',
        title: 'KOSMOS V2.0 Architecture',
        description: 'System design, governance framework, and technical architecture',
        slug: '/02-architecture',
      },
      items: [
        {type: 'autogenerated', dirName: '02-architecture'},
      ],
    },
  ],

  // Agents Sidebar (Auto-generated)
  agentsSidebar: [
    {
      type: 'category',
      label: 'Agents',
      link: {
        type: 'generated-index',
        title: 'KOSMOS Agents',
        description: '11 specialized AI agents that power KOSMOS V2.0',
        slug: '/agents',
      },
      items: [
        {type: 'autogenerated', dirName: '03-agents'},
      ],
    },
  ],

  // API Sidebar (Auto-generated from FastAPI)
  apiSidebar: [
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'generated-index',
        title: 'KOSMOS V2.0 API',
        description: 'REST API endpoints, authentication, and WebSocket APIs',
        slug: '/04-api',
      },
      items: [
        {type: 'autogenerated', dirName: '04-api'},
      ],
    },
  ],

  // MCP Servers Sidebar (Auto-generated)
  mcpSidebar: [
    {
      type: 'category',
      label: 'MCP Servers',
      link: {
        type: 'generated-index',
        title: 'MCP Integration Hub',
        description: '88 MCP servers across 9 domains for comprehensive tool integration',
        slug: '/05-mcp-servers',
      },
      items: [
        {type: 'autogenerated', dirName: '05-mcp-servers'},
      ],
    },
  ],

  // Frontend Sidebar (Auto-generated)
  frontendSidebar: [
    {
      type: 'category',
      label: 'Frontend Components',
      link: {
        type: 'generated-index',
        title: 'Frontend Components',
        description: 'React/Next.js components documentation',
        slug: '/06-frontend',
      },
      items: [
        {type: 'autogenerated', dirName: '06-frontend'},
      ],
    },
  ],

  // Database Sidebar (Auto-generated)
  databaseSidebar: [
    {
      type: 'category',
      label: 'Database',
      link: {
        type: 'generated-index',
        title: 'Database Schema',
        description: 'PostgreSQL schema, models, and ERD documentation',
        slug: '/07-database',
      },
      items: [
        {type: 'autogenerated', dirName: '07-database'},
      ],
    },
  ],

  // Configuration Sidebar (Auto-generated)
  configSidebar: [
    {
      type: 'category',
      label: 'Configuration',
      link: {
        type: 'generated-index',
        title: 'Configuration Reference',
        description: 'Environment variables, settings, and deployment configuration',
        slug: '/08-configuration',
      },
      items: [
        {type: 'autogenerated', dirName: '08-configuration'},
      ],
    },
  ],

  // Governance Sidebar (Manual)
  governanceSidebar: [
    {
      type: 'category',
      label: 'Governance & Meta',
      link: {
        type: 'generated-index',
        title: 'Governance & Project Meta',
        description: 'Gap analysis, roadmap, and contributing guidelines',
        slug: '/09-governance',
      },
      items: [
        {type: 'autogenerated', dirName: '09-governance'},
      ],
    },
  ],
};

export default sidebars;
