#!/bin/bash
# KOSMOS AEOS - Post-create script for Codespaces
# Runs once when the container is created

set -e

echo "🚀 KOSMOS AEOS - Setting up development environment..."

# Navigate to workspace
cd /workspaces/${LOCAL_WORKSPACE_FOLDER_BASENAME:-kosmos}

# Backend setup
echo "📦 Installing Python dependencies..."
cd implementation/backend

# Create virtual environment if it doesn't exist
if [ ! -d ".venv" ]; then
    python -m venv .venv
fi

# Activate virtual environment
source .venv/bin/activate

# Install dependencies
if [ -f "pyproject.toml" ]; then
    pip install -e ".[dev]"
elif [ -f "requirements.txt" ]; then
    pip install -r requirements.txt
fi

# Install dev dependencies
pip install pytest pytest-cov pytest-asyncio httpx black isort ruff mypy

cd ../..

# Frontend setup
echo "📦 Installing Node.js dependencies..."
cd implementation/frontend

# Install dependencies
npm install

# Build types
npm run build --if-present || true

cd ../..

# Wait for database
echo "⏳ Waiting for PostgreSQL to be ready..."
until pg_isready -h db -p 5432 -U kosmos 2>/dev/null; do
    sleep 1
done
echo "✅ PostgreSQL is ready!"

# Run database migrations
echo "🗃️ Running database migrations..."
cd implementation/backend
if [ -f "alembic.ini" ]; then
    alembic upgrade head || echo "⚠️ Alembic migrations skipped (might not be configured)"
fi
cd ../..

# Redis check
echo "⏳ Waiting for Redis to be ready..."
until redis-cli -h redis ping 2>/dev/null; do
    sleep 1
done
echo "✅ Redis is ready!"

# Create .env file if not exists
if [ ! -f ".env" ]; then
    echo "📝 Creating .env file from template..."
    if [ -f ".env.example" ]; then
        cp .env.example .env
    else
        cat > .env << 'EOF'
# KOSMOS AEOS Environment Configuration
# Generated by Codespaces setup

# Database
DATABASE_URL=postgresql://kosmos:kosmos_dev@db:5432/kosmos_db

# Redis
REDIS_URL=redis://redis:6379/0

# API Keys (add your own)
ANTHROPIC_API_KEY=
OPENAI_API_KEY=

# Security
JWT_SECRET=dev-secret-change-in-production
ENCRYPTION_KEY=dev-encryption-key-change-in-production

# Environment
NODE_ENV=development
PYTHON_ENV=development
DEBUG=true
EOF
    fi
fi

# Git configuration
echo "🔧 Configuring Git..."
git config --global --add safe.directory /workspaces/${LOCAL_WORKSPACE_FOLDER_BASENAME:-kosmos}
git config pull.rebase false

echo ""
echo "✅ KOSMOS AEOS development environment is ready!"
echo ""
echo "Quick start commands:"
echo "  - Backend:  cd implementation/backend && uvicorn main:app --reload"
echo "  - Frontend: cd implementation/frontend && npm run dev"
echo "  - Tests:    cd implementation/backend && pytest"
echo ""
echo "Services:"
echo "  - Frontend:   http://localhost:3000"
echo "  - Backend:    http://localhost:8000"
echo "  - API Docs:   http://localhost:8000/docs"
echo "  - PgAdmin:    http://localhost:8080"
echo "  - Storybook:  http://localhost:6006"
echo ""
