#!/bin/bash
# KOSMOS DAR Morning Review Script
# Reviews overnight async agent outputs, validates completed work, generates daily task list

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "🌅 KOSMOS DAR Morning Review"
echo "=============================="
echo ""

# Check for completed async tasks
echo "📋 Checking overnight async agent outputs..."
if [ -d "$PROJECT_ROOT/.agent-outputs" ]; then
    COMPLETED=$(find "$PROJECT_ROOT/.agent-outputs" -name "*.completed" -mtime -1 | wc -l)
    echo "  Found $COMPLETED completed tasks"
    
    if [ "$COMPLETED" -gt 0 ]; then
        echo ""
        echo "✅ Completed Tasks:"
        find "$PROJECT_ROOT/.agent-outputs" -name "*.completed" -mtime -1 | while read file; do
            echo "  - $(basename "$file" .completed)"
        done
    fi
else
    echo "  No .agent-outputs directory found"
fi

echo ""

# Validate completed work
echo "🔍 Validating completed work..."
if command -v python3 &> /dev/null; then
    # Run tests if available
    if [ -f "$PROJECT_ROOT/implementation/backend/pytest.ini" ] || [ -f "$PROJECT_ROOT/pyproject.toml" ]; then
        echo "  Running tests..."
        cd "$PROJECT_ROOT/implementation/backend"
        python3 -m pytest tests/ -v --tb=short 2>&1 | head -20 || echo "  ⚠️  Some tests failed (see output above)"
    fi
else
    echo "  ⚠️  Python3 not found, skipping validation"
fi

echo ""

# Generate daily task list
echo "📝 Generating daily task list..."
TODAY=$(date +%Y-%m-%d)
TASK_FILE="$PROJECT_ROOT/.tasks-$TODAY.md"

cat > "$TASK_FILE" << EOF
# Daily Tasks - $TODAY

## High Priority
- [ ] Review and merge completed async work
- [ ] Review overnight agent outputs
- [ ] Update ACTION_PLAN.md progress

## Medium Priority
- [ ] Create specifications for complex features
- [ ] Review and approve pending specs
- [ ] Update context files with learnings

## Low Priority
- [ ] Code cleanup and refactoring
- [ ] Documentation updates
- [ ] Test coverage improvements

## Notes
- Generated by morning_review.sh
EOF

echo "  ✅ Task list created: $TASK_FILE"

echo ""
echo "📊 Review Summary"
echo "=================="
echo "Date: $TODAY"
echo "Completed Tasks: $COMPLETED"
echo "Task List: $TASK_FILE"
echo ""
echo "✅ Morning review complete!"
